spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: YOUR_CLIENT_ID
            clientSecret: YOUR_CLIENT_SECRET
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope:
              - profile
              - https://www.googleapis.com/auth/calendar
            redirectUriTemplate: "{baseUrl}/gcaloauth/oauth2callback"
            grantType: refresh_token
            resource:
              userInfoUri: https://www.googleapis.com/userinfo/v2/me

server:
  port: 8090